# https://www.favicon.cc/?action=icon&file_id=17897
baseurl = "//anasantosgrooming.com/"
languageCode = "pt-PT"
title = "Ana Santos Grooming"
theme = "creative"
googleAnalytics = "G-EVFED8D782"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Ana Santos"
	description = "Dog and Cat Groomer"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Ana Santos Grooming"

		[params.navigation.links]
			about     = "Sobre"
			services  = "Locais"
			portfolio = "Raças"
			#portfolio = "Portfólio"
			contact   = "Contacto"


	# Hero section
	# https://pixabay.com/photos/dog-cat-pets-animals-friends-2606759/
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Cuide do bem-estar e estética do seu animal"
		subtitle   = "Ana Santos é uma dog groomer com mais de quatro anos de experiência profissional em banhos e tosquias de raça, a zelar pelo bem-estar e felicidade do seu animal."
		buttonText = "Saber mais"


	# About section
	[params.about]
		headline    = "Grooming de Cães e Gatos"
		description = "Banhos, tosquias, cortes de raça, manutenção do pêlo, cortes de unhas. O bem-estar do seu animal é a minha prioridade!"
		buttonText  = "Onde?"
		buttonLink = "#services"


	# Service section
	[params.services]
		headline = "Disponível para serviço em..."

        [[params.services.list]]
            icon = "fa-paw"
            title = "Lojas de Animais"
            description = "Se é dono de uma loja de animais e necessita de serviços de dog grooming, [contacte](#contact)."

		[[params.services.list]]
            icon = "fa-stethoscope"
            title = "Clínicas Veterinárias"
            description = "Serviços de tosquia com máquina, tesoura, stripping, cortes de raça &ndash; equipamento próprio. [Entre em contacto](#contact)!"

		[[params.services.list]]
            icon = "fa-envelope"
            title = "Outros Locais"
            description = "Caso tenha interesse em serviços de dog grooming noutro local, [contacte](#contact)."

    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	# [params.aside]
	# 	headline = "Veja o Portfólio Completo"

	# 	[params.aside.button]
	# 		text = "Descarregar (apenas em loja)"
	# 		link = "//anasantosgrooming.com/anasantos-grooming-portfolio.pdf"

	# Contact section
	[params.contact]
		headline = "Contacto"
		description = "Para marcações para o seu animal, por favor contacte a respetiva loja ou clínica. Ou, se desejar contratar o serviço de dog grooming para a sua loja ou clínica, por favor utilize o seguinte contacto."
		#phone = "123-456-6789"
		email = "mail@anasantosgrooming.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
